Player.create(username: "MikeMcF", email: "MMcFaddin@aol.com")
Player.create(username: "KatE", email: "k_evans@aol.com")
Player.create(username: "HeyDan", email: "heydanhey@aol.com")
Player.create(username: "ptr_pumpkin_etr", email: "peter_jang@aol.com")
Player.create(username: "JNix", email: "josh_nixon@aol.com")
Player.create(username: "jadzia_fan", email: "margaret_dax@aol.com")
Score.create(username: "MikeMcF", correct: 10, incorrect: 11)
Score.create(username: "KatE", correct: 8, incorrect: 13)
Score.create(username: "HeyDan", correct: 15, incorrect: 6)
Score.create(username: "ptr_pumpkin_etr", correct: 17, incorrect: 4)
Score.create(username: "JNix", correct: 12, incorrect: 9)
Score.create(username: "jadzia_fan", correct: 19, incorrect: 2)